# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57eff199ab2881d71208e3458ab3f470deef0285e93d31b687b487145b891f49f6e785387f459e56aa7365441a843d07450eca9116a2c2d00ded5a322c497f93

test:
  secret_key_base: 895f9ba2c4c8814b44f3b574a70c83210e15c9ab3c22fdb7145af86f21b8863c944aa954636a73dce913e9c0ab15da3fcaab44f4c99572746fbdebf7ebfcc5bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
